namespace: zcash
containers:
  # testnet:
  #   image: baseboxorg/zcash:latest
  #   # ports:
  #   # TODO: what are the right ports?
  #   volumes:
  #    - "data/testnet:/home/zcash/.zcash"
  #    - "data/zcash-params:/home/zcash/.zcash-params"
  #    - "testnet.conf:/config/zcash.conf:ro"
  mainnet:
    image: baseboxorg/zcash:latest
    ports:
     - "8233:8233/tcp"
    volumes:
     - "data/mainnet:/home/zcash/.zcash"
     - "data/zcash-params:/home/zcash/.zcash-params"
     - "mainnet.conf:/config/zcash.conf:ro"
